#!/usr/bin/env bash
# add_style.sh: scaffold a new style directory for a brand.
# This script provides the operator-facing flag handling and file scaffolding.
# The actual DESIGN.md content is generated by the host agent based on the
# operator's --description and/or --refs inputs (see references/style-system.md
# for the agent prompt contract).
#
# Exit codes:
#   0 ok
#   1 brand not found
#   2 usage error
#   3 style already exists (without --force)

set -euo pipefail

usage() {
  cat >&2 <<USAGE
usage: add_style.sh --brand <slug> --style <name> \\
       [--description "..."] [--refs path1.png,path2.png] [--force]

at least one of --description or --refs must be provided.

writes:
  <brands_root>/<slug>/styles/<style-name>/DESIGN.md
  <brands_root>/<slug>/styles/<style-name>/refs/*.png

agent contract documented in references/style-system.md.
USAGE
  exit 2
}

BRAND=""
STYLE=""
DESCRIPTION=""
REFS=""
FORCE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --brand) BRAND="${2:-}"; shift 2 ;;
    --style) STYLE="${2:-}"; shift 2 ;;
    --description) DESCRIPTION="${2:-}"; shift 2 ;;
    --refs) REFS="${2:-}"; shift 2 ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage ;;
    *) echo "unknown flag: $1" >&2; usage ;;
  esac
done

if [ -z "$BRAND" ] || [ -z "$STYLE" ]; then
  usage
fi
if [ -z "$DESCRIPTION" ] && [ -z "$REFS" ]; then
  echo "[FAIL] one of --description or --refs is required" >&2
  usage
fi
if ! [[ "$STYLE" =~ ^[a-z][a-z0-9_]*$ ]]; then
  echo "[FAIL] style name must be lowercase alnum + underscore, starting alpha (matches snake_case convention)" >&2
  exit 2
fi

KIT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
source "$(dirname "$0")/_resolve_brands_root.sh"
BRAND_DIR="$BRANDS_ROOT/$BRAND"

if [ ! -d "$BRAND_DIR" ]; then
  echo "[FAIL] brand workspace not found: $BRAND_DIR" >&2
  exit 1
fi

STYLE_DIR="$BRAND_DIR/styles/$STYLE"
if [ -d "$STYLE_DIR" ] && [ "$FORCE" -ne 1 ]; then
  echo "[FAIL] style already exists: $STYLE_DIR (use --force to overwrite)" >&2
  exit 3
fi

mkdir -p "$STYLE_DIR/refs"

# Copy any provided refs.
if [ -n "$REFS" ]; then
  IFS=',' read -ra REF_ARRAY <<< "$REFS"
  for ref in "${REF_ARRAY[@]}"; do
    if [ ! -f "$ref" ]; then
      echo "[WARN] ref not found, skipping: $ref" >&2
      continue
    fi
    cp "$ref" "$STYLE_DIR/refs/$(basename "$ref")"
  done
fi

# Write a stub DESIGN.md. The host agent reads description + refs and rewrites
# this file with proper YAML tokens + markdown body. Until the agent runs, the
# stub is parseable and inheriting from brand defaults.
cat > "$STYLE_DIR/DESIGN.md" <<EOF
---
name: $STYLE
extends: brand
---

# Style: $STYLE

> **Stub.** This file was scaffolded by add_style.sh. Run the host agent with
> the style-extraction prompt (references/style-system.md) to populate tokens
> and rationale.

**Operator inputs at scaffold time:**

- description: $(echo "$DESCRIPTION" | sed 's/^/  /' | tr '\n' ' ' | sed 's/  */ /g')
- refs supplied: $(ls "$STYLE_DIR/refs" 2>/dev/null | tr '\n' ', ' | sed 's/, $//')
EOF

echo "[PASS] scaffolded style at $STYLE_DIR"
echo "[INFO] next: invoke host agent with the style-extraction prompt to populate DESIGN.md"
echo "       see references/style-system.md for the agent contract"
